// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/liyubo06/resumeOptim_claude/backend/services/ai-service/internal/biz"
	"github.com/liyubo06/resumeOptim_claude/backend/services/ai-service/internal/conf"
	"github.com/liyubo06/resumeOptim_claude/backend/services/ai-service/internal/data"
	"github.com/liyubo06/resumeOptim_claude/backend/services/ai-service/internal/server"
	"github.com/liyubo06/resumeOptim_claude/backend/services/ai-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, ai *conf.AI, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	aiRepo := data.NewAIRepo(dataData, logger)
	aiUsecase := biz.NewAIUsecase(aiRepo, ai, logger)
	aiService := service.NewAIService(aiUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, aiService, logger)
	httpServer := server.NewHTTPServer(confServer, aiService, logger)
	registrar := server.NewRegistrar(bootstrap)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
