// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.27.3
// source: backend/services/parser-service/api/parser/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 解析服务错误码
type ErrorReason int32

const (
	// 文件不存在
	ErrorReason_FILE_NOT_FOUND ErrorReason = 0
	// 不支持的文件格式
	ErrorReason_UNSUPPORTED_FILE_TYPE ErrorReason = 1
	// 文件损坏或无法读取
	ErrorReason_FILE_CORRUPTED ErrorReason = 2
	// 解析失败
	ErrorReason_PARSE_FAILED ErrorReason = 3
	// 任务不存在
	ErrorReason_TASK_NOT_FOUND ErrorReason = 4
	// 任务正在处理中
	ErrorReason_TASK_PROCESSING ErrorReason = 5
	// 文件太大
	ErrorReason_FILE_TOO_LARGE ErrorReason = 6
	// 解析超时
	ErrorReason_PARSE_TIMEOUT ErrorReason = 7
	// 文档密码保护
	ErrorReason_DOCUMENT_PROTECTED ErrorReason = 8
	// 内容为空
	ErrorReason_EMPTY_CONTENT ErrorReason = 9
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "FILE_NOT_FOUND",
		1: "UNSUPPORTED_FILE_TYPE",
		2: "FILE_CORRUPTED",
		3: "PARSE_FAILED",
		4: "TASK_NOT_FOUND",
		5: "TASK_PROCESSING",
		6: "FILE_TOO_LARGE",
		7: "PARSE_TIMEOUT",
		8: "DOCUMENT_PROTECTED",
		9: "EMPTY_CONTENT",
	}
	ErrorReason_value = map[string]int32{
		"FILE_NOT_FOUND":        0,
		"UNSUPPORTED_FILE_TYPE": 1,
		"FILE_CORRUPTED":        2,
		"PARSE_FAILED":          3,
		"TASK_NOT_FOUND":        4,
		"TASK_PROCESSING":       5,
		"FILE_TOO_LARGE":        6,
		"PARSE_TIMEOUT":         7,
		"DOCUMENT_PROTECTED":    8,
		"EMPTY_CONTENT":         9,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_services_parser_service_api_parser_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_backend_services_parser_service_api_parser_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_backend_services_parser_service_api_parser_v1_error_reason_proto protoreflect.FileDescriptor

const file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"@backend/services/parser-service/api/parser/v1/error_reason.proto\x12\rapi.parser.v1\x1a\x13errors/errors.proto*\x9f\x02\n" +
	"\vErrorReason\x12\x18\n" +
	"\x0eFILE_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x1f\n" +
	"\x15UNSUPPORTED_FILE_TYPE\x10\x01\x1a\x04\xa8E\x90\x03\x12\x18\n" +
	"\x0eFILE_CORRUPTED\x10\x02\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fPARSE_FAILED\x10\x03\x1a\x04\xa8E\xf4\x03\x12\x18\n" +
	"\x0eTASK_NOT_FOUND\x10\x04\x1a\x04\xa8E\x94\x03\x12\x19\n" +
	"\x0fTASK_PROCESSING\x10\x05\x1a\x04\xa8E\xca\x01\x12\x18\n" +
	"\x0eFILE_TOO_LARGE\x10\x06\x1a\x04\xa8E\x9d\x03\x12\x17\n" +
	"\rPARSE_TIMEOUT\x10\a\x1a\x04\xa8E\x98\x03\x12\x1c\n" +
	"\x12DOCUMENT_PROTECTED\x10\b\x1a\x04\xa8E\x90\x03\x12\x17\n" +
	"\rEMPTY_CONTENT\x10\t\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03BTZRgithub.com/lyb88999/resume_helper/backend/services/parser-service/api/parser/v1;v1b\x06proto3"

var (
	file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDescOnce sync.Once
	file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDescData []byte
)

func file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDescGZIP() []byte {
	file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDesc), len(file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDesc)))
	})
	return file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDescData
}

var file_backend_services_parser_service_api_parser_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_services_parser_service_api_parser_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.parser.v1.ErrorReason
}
var file_backend_services_parser_service_api_parser_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_services_parser_service_api_parser_v1_error_reason_proto_init() }
func file_backend_services_parser_service_api_parser_v1_error_reason_proto_init() {
	if File_backend_services_parser_service_api_parser_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDesc), len(file_backend_services_parser_service_api_parser_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_services_parser_service_api_parser_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_backend_services_parser_service_api_parser_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_backend_services_parser_service_api_parser_v1_error_reason_proto_enumTypes,
	}.Build()
	File_backend_services_parser_service_api_parser_v1_error_reason_proto = out.File
	file_backend_services_parser_service_api_parser_v1_error_reason_proto_goTypes = nil
	file_backend_services_parser_service_api_parser_v1_error_reason_proto_depIdxs = nil
}
