// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.27.3
// source: backend/services/parser-service/api/parser/v1/parser.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 解析文档请求
type ParseDocumentRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FilePath string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileType string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	ResumeId string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	UserId   string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 解析选项
	Options       *ParseOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDocumentRequest) Reset() {
	*x = ParseDocumentRequest{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDocumentRequest) ProtoMessage() {}

func (x *ParseDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDocumentRequest.ProtoReflect.Descriptor instead.
func (*ParseDocumentRequest) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseDocumentRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ParseDocumentRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ParseDocumentRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *ParseDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParseDocumentRequest) GetOptions() *ParseOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// 解析选项
type ParseOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExtractImages  bool                   `protobuf:"varint,1,opt,name=extract_images,json=extractImages,proto3" json:"extract_images,omitempty"`   // 是否提取图片
	CleanText      bool                   `protobuf:"varint,2,opt,name=clean_text,json=cleanText,proto3" json:"clean_text,omitempty"`               // 是否清洗文本
	TargetLanguage string                 `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"` // 目标语言 zh-CN, en-US
	SkipSections   []string               `protobuf:"bytes,4,rep,name=skip_sections,json=skipSections,proto3" json:"skip_sections,omitempty"`       // 跳过的章节
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseOptions) Reset() {
	*x = ParseOptions{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseOptions) ProtoMessage() {}

func (x *ParseOptions) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseOptions.ProtoReflect.Descriptor instead.
func (*ParseOptions) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseOptions) GetExtractImages() bool {
	if x != nil {
		return x.ExtractImages
	}
	return false
}

func (x *ParseOptions) GetCleanText() bool {
	if x != nil {
		return x.CleanText
	}
	return false
}

func (x *ParseOptions) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

func (x *ParseOptions) GetSkipSections() []string {
	if x != nil {
		return x.SkipSections
	}
	return nil
}

// 解析文档响应
type ParseDocumentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // processing, completed, failed
	Content       *ParsedContent         `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDocumentReply) Reset() {
	*x = ParseDocumentReply{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDocumentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDocumentReply) ProtoMessage() {}

func (x *ParseDocumentReply) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDocumentReply.ProtoReflect.Descriptor instead.
func (*ParseDocumentReply) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{2}
}

func (x *ParseDocumentReply) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ParseDocumentReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ParseDocumentReply) GetContent() *ParsedContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ParseDocumentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseDocumentReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 解析内容
type ParsedContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonalInfo  *PersonalInfo          `protobuf:"bytes,1,opt,name=personal_info,json=personalInfo,proto3" json:"personal_info,omitempty"`
	Education     []*Education           `protobuf:"bytes,2,rep,name=education,proto3" json:"education,omitempty"`
	Experience    []*Experience          `protobuf:"bytes,3,rep,name=experience,proto3" json:"experience,omitempty"`
	Projects      []*Project             `protobuf:"bytes,4,rep,name=projects,proto3" json:"projects,omitempty"`
	Skills        *Skills                `protobuf:"bytes,5,opt,name=skills,proto3" json:"skills,omitempty"`
	RawText       string                 `protobuf:"bytes,6,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	Metadata      *ParseMetadata         `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedContent) Reset() {
	*x = ParsedContent{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedContent) ProtoMessage() {}

func (x *ParsedContent) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedContent.ProtoReflect.Descriptor instead.
func (*ParsedContent) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{3}
}

func (x *ParsedContent) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *ParsedContent) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *ParsedContent) GetExperience() []*Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *ParsedContent) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ParsedContent) GetSkills() *Skills {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ParsedContent) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *ParsedContent) GetMetadata() *ParseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 个人信息
type PersonalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Nationality   string                 `protobuf:"bytes,7,opt,name=nationality,proto3" json:"nationality,omitempty"`
	SocialLinks   []string               `protobuf:"bytes,8,rep,name=social_links,json=socialLinks,proto3" json:"social_links,omitempty"` // LinkedIn, GitHub等
	AvatarUrl     string                 `protobuf:"bytes,9,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{4}
}

func (x *PersonalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonalInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PersonalInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PersonalInfo) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *PersonalInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PersonalInfo) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *PersonalInfo) GetSocialLinks() []string {
	if x != nil {
		return x.SocialLinks
	}
	return nil
}

func (x *PersonalInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// 教育背景
type Education struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        string                 `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Degree        string                 `protobuf:"bytes,2,opt,name=degree,proto3" json:"degree,omitempty"` // 学位：学士、硕士、博士
	Major         string                 `protobuf:"bytes,3,opt,name=major,proto3" json:"major,omitempty"`   // 专业
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Gpa           string                 `protobuf:"bytes,6,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Courses       []string               `protobuf:"bytes,8,rep,name=courses,proto3" json:"courses,omitempty"` // 主要课程
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{5}
}

func (x *Education) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *Education) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Education) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Education) GetGpa() string {
	if x != nil {
		return x.Gpa
	}
	return ""
}

func (x *Education) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Education) GetCourses() []string {
	if x != nil {
		return x.Courses
	}
	return nil
}

// 工作经历
type Experience struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Company          string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Position         string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	StartDate        string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate          string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Location         string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Department       string                 `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`
	Responsibilities []string               `protobuf:"bytes,7,rep,name=responsibilities,proto3" json:"responsibilities,omitempty"` // 工作职责
	Achievements     []string               `protobuf:"bytes,8,rep,name=achievements,proto3" json:"achievements,omitempty"`         // 工作成就
	Technologies     []string               `protobuf:"bytes,9,rep,name=technologies,proto3" json:"technologies,omitempty"`         // 使用技术
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{6}
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Experience) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Experience) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Experience) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Experience) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Experience) GetResponsibilities() []string {
	if x != nil {
		return x.Responsibilities
	}
	return nil
}

func (x *Experience) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

func (x *Experience) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

// 项目经历
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // 角色
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Technologies  []string               `protobuf:"bytes,6,rep,name=technologies,proto3" json:"technologies,omitempty"` // 技术栈
	Achievements  []string               `protobuf:"bytes,7,rep,name=achievements,proto3" json:"achievements,omitempty"` // 项目成果
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`                   // 项目链接
	Company       string                 `protobuf:"bytes,9,opt,name=company,proto3" json:"company,omitempty"`           // 所属公司
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{7}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Project) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Project) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *Project) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

func (x *Project) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Project) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

// 技能
type Skills struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Categories     []*SkillCategory       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Languages      []string               `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`           // 语言能力
	Certifications []string               `protobuf:"bytes,3,rep,name=certifications,proto3" json:"certifications,omitempty"` // 证书
	Awards         []string               `protobuf:"bytes,4,rep,name=awards,proto3" json:"awards,omitempty"`                 // 奖项
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Skills) Reset() {
	*x = Skills{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skills) ProtoMessage() {}

func (x *Skills) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skills.ProtoReflect.Descriptor instead.
func (*Skills) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{8}
}

func (x *Skills) GetCategories() []*SkillCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Skills) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *Skills) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *Skills) GetAwards() []string {
	if x != nil {
		return x.Awards
	}
	return nil
}

// 技能分类
type SkillCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // 分类名称：编程语言、框架、工具等
	Skills        []*SkillItem           `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillCategory) Reset() {
	*x = SkillCategory{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCategory) ProtoMessage() {}

func (x *SkillCategory) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCategory.ProtoReflect.Descriptor instead.
func (*SkillCategory) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{9}
}

func (x *SkillCategory) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SkillCategory) GetSkills() []*SkillItem {
	if x != nil {
		return x.Skills
	}
	return nil
}

// 技能项
type SkillItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`  // 熟练度：熟练、精通、了解
	Years         int32                  `protobuf:"varint,3,opt,name=years,proto3" json:"years,omitempty"` // 使用年限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillItem) Reset() {
	*x = SkillItem{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillItem) ProtoMessage() {}

func (x *SkillItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillItem.ProtoReflect.Descriptor instead.
func (*SkillItem) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{10}
}

func (x *SkillItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillItem) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SkillItem) GetYears() int32 {
	if x != nil {
		return x.Years
	}
	return 0
}

// 解析元数据
type ParseMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileSize        string                 `protobuf:"bytes,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	PageCount       int32                  `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	ParseDuration   string                 `protobuf:"bytes,3,opt,name=parse_duration,json=parseDuration,proto3" json:"parse_duration,omitempty"`
	ParserVersion   string                 `protobuf:"bytes,4,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	Warnings        []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ConfidenceScore int32                  `protobuf:"varint,6,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"` // 解析置信度 0-100
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParseMetadata) Reset() {
	*x = ParseMetadata{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseMetadata) ProtoMessage() {}

func (x *ParseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseMetadata.ProtoReflect.Descriptor instead.
func (*ParseMetadata) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{11}
}

func (x *ParseMetadata) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *ParseMetadata) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *ParseMetadata) GetParseDuration() string {
	if x != nil {
		return x.ParseDuration
	}
	return ""
}

func (x *ParseMetadata) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *ParseMetadata) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ParseMetadata) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

// 获取解析状态请求
type GetParseStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParseStatusRequest) Reset() {
	*x = GetParseStatusRequest{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParseStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParseStatusRequest) ProtoMessage() {}

func (x *GetParseStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParseStatusRequest.ProtoReflect.Descriptor instead.
func (*GetParseStatusRequest) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{12}
}

func (x *GetParseStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 获取解析状态响应
type GetParseStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Content       *ParsedContent         `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"` // 进度 0-100
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParseStatusReply) Reset() {
	*x = GetParseStatusReply{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParseStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParseStatusReply) ProtoMessage() {}

func (x *GetParseStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParseStatusReply.ProtoReflect.Descriptor instead.
func (*GetParseStatusReply) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{13}
}

func (x *GetParseStatusReply) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetParseStatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetParseStatusReply) GetContent() *ParsedContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetParseStatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetParseStatusReply) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetParseStatusReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetParseStatusReply) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 健康检查请求
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{14}
}

// 健康检查响应
type HealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP(), []int{15}
}

func (x *HealthReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthReply) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthReply) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_backend_services_parser_service_api_parser_v1_parser_proto protoreflect.FileDescriptor

const file_backend_services_parser_service_api_parser_v1_parser_proto_rawDesc = "" +
	"\n" +
	":backend/services/parser-service/api/parser/v1/parser.proto\x12\rapi.parser.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xf8\x01\n" +
	"\x14ParseDocumentRequest\x12$\n" +
	"\tfile_path\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bfilePath\x12;\n" +
	"\tfile_type\x18\x02 \x01(\tB\x1e\xfaB\x1br\x19R\x03pdfR\x04docxR\x03docR\x03txtR\x02mdR\bfileType\x12$\n" +
	"\tresume_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bresumeId\x12 \n" +
	"\auser_id\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x125\n" +
	"\aoptions\x18\x05 \x01(\v2\x1b.api.parser.v1.ParseOptionsR\aoptions\"\xa2\x01\n" +
	"\fParseOptions\x12%\n" +
	"\x0eextract_images\x18\x01 \x01(\bR\rextractImages\x12\x1d\n" +
	"\n" +
	"clean_text\x18\x02 \x01(\bR\tcleanText\x12'\n" +
	"\x0ftarget_language\x18\x03 \x01(\tR\x0etargetLanguage\x12#\n" +
	"\rskip_sections\x18\x04 \x03(\tR\fskipSections\"\xd2\x01\n" +
	"\x12ParseDocumentReply\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x126\n" +
	"\acontent\x18\x03 \x01(\v2\x1c.api.parser.v1.ParsedContentR\acontent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xfc\x02\n" +
	"\rParsedContent\x12@\n" +
	"\rpersonal_info\x18\x01 \x01(\v2\x1b.api.parser.v1.PersonalInfoR\fpersonalInfo\x126\n" +
	"\teducation\x18\x02 \x03(\v2\x18.api.parser.v1.EducationR\teducation\x129\n" +
	"\n" +
	"experience\x18\x03 \x03(\v2\x19.api.parser.v1.ExperienceR\n" +
	"experience\x122\n" +
	"\bprojects\x18\x04 \x03(\v2\x16.api.parser.v1.ProjectR\bprojects\x12-\n" +
	"\x06skills\x18\x05 \x01(\v2\x15.api.parser.v1.SkillsR\x06skills\x12\x19\n" +
	"\braw_text\x18\x06 \x01(\tR\arawText\x128\n" +
	"\bmetadata\x18\a \x01(\v2\x1c.api.parser.v1.ParseMetadataR\bmetadata\"\x83\x02\n" +
	"\fPersonalInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12 \n" +
	"\vnationality\x18\a \x01(\tR\vnationality\x12!\n" +
	"\fsocial_links\x18\b \x03(\tR\vsocialLinks\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\t \x01(\tR\tavatarUrl\"\xd9\x01\n" +
	"\tEducation\x12\x16\n" +
	"\x06school\x18\x01 \x01(\tR\x06school\x12\x16\n" +
	"\x06degree\x18\x02 \x01(\tR\x06degree\x12\x14\n" +
	"\x05major\x18\x03 \x01(\tR\x05major\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x10\n" +
	"\x03gpa\x18\x06 \x01(\tR\x03gpa\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x18\n" +
	"\acourses\x18\b \x03(\tR\acourses\"\xac\x02\n" +
	"\n" +
	"Experience\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1e\n" +
	"\n" +
	"department\x18\x06 \x01(\tR\n" +
	"department\x12*\n" +
	"\x10responsibilities\x18\a \x03(\tR\x10responsibilities\x12\"\n" +
	"\fachievements\x18\b \x03(\tR\fachievements\x12\"\n" +
	"\ftechnologies\x18\t \x03(\tR\ftechnologies\"\x81\x02\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\ftechnologies\x18\x06 \x03(\tR\ftechnologies\x12\"\n" +
	"\fachievements\x18\a \x03(\tR\fachievements\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x18\n" +
	"\acompany\x18\t \x01(\tR\acompany\"\xa4\x01\n" +
	"\x06Skills\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.api.parser.v1.SkillCategoryR\n" +
	"categories\x12\x1c\n" +
	"\tlanguages\x18\x02 \x03(\tR\tlanguages\x12&\n" +
	"\x0ecertifications\x18\x03 \x03(\tR\x0ecertifications\x12\x16\n" +
	"\x06awards\x18\x04 \x03(\tR\x06awards\"]\n" +
	"\rSkillCategory\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x120\n" +
	"\x06skills\x18\x02 \x03(\v2\x18.api.parser.v1.SkillItemR\x06skills\"K\n" +
	"\tSkillItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x14\n" +
	"\x05years\x18\x03 \x01(\x05R\x05years\"\xe0\x01\n" +
	"\rParseMetadata\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\tR\bfileSize\x12\x1d\n" +
	"\n" +
	"page_count\x18\x02 \x01(\x05R\tpageCount\x12%\n" +
	"\x0eparse_duration\x18\x03 \x01(\tR\rparseDuration\x12%\n" +
	"\x0eparser_version\x18\x04 \x01(\tR\rparserVersion\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12)\n" +
	"\x10confidence_score\x18\x06 \x01(\x05R\x0fconfidenceScore\"9\n" +
	"\x15GetParseStatusRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\"\xaa\x02\n" +
	"\x13GetParseStatusReply\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x126\n" +
	"\acontent\x18\x03 \x01(\v2\x1c.api.parser.v1.ParsedContentR\acontent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x0f\n" +
	"\rHealthRequest\"y\n" +
	"\vHealthReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xe4\x02\n" +
	"\rParserService\x12x\n" +
	"\rParseDocument\x12#.api.parser.v1.ParseDocumentRequest\x1a!.api.parser.v1.ParseDocumentReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/parser/parse\x12\x83\x01\n" +
	"\x0eGetParseStatus\x12$.api.parser.v1.GetParseStatusRequest\x1a\".api.parser.v1.GetParseStatusReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/parser/status/{task_id}\x12S\n" +
	"\x06Health\x12\x1c.api.parser.v1.HealthRequest\x1a\x1a.api.parser.v1.HealthReply\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthBTZRgithub.com/lyb88999/resume_helper/backend/services/parser-service/api/parser/v1;v1b\x06proto3"

var (
	file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescOnce sync.Once
	file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescData []byte
)

func file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescGZIP() []byte {
	file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescOnce.Do(func() {
		file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_services_parser_service_api_parser_v1_parser_proto_rawDesc), len(file_backend_services_parser_service_api_parser_v1_parser_proto_rawDesc)))
	})
	return file_backend_services_parser_service_api_parser_v1_parser_proto_rawDescData
}

var file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_backend_services_parser_service_api_parser_v1_parser_proto_goTypes = []any{
	(*ParseDocumentRequest)(nil),  // 0: api.parser.v1.ParseDocumentRequest
	(*ParseOptions)(nil),          // 1: api.parser.v1.ParseOptions
	(*ParseDocumentReply)(nil),    // 2: api.parser.v1.ParseDocumentReply
	(*ParsedContent)(nil),         // 3: api.parser.v1.ParsedContent
	(*PersonalInfo)(nil),          // 4: api.parser.v1.PersonalInfo
	(*Education)(nil),             // 5: api.parser.v1.Education
	(*Experience)(nil),            // 6: api.parser.v1.Experience
	(*Project)(nil),               // 7: api.parser.v1.Project
	(*Skills)(nil),                // 8: api.parser.v1.Skills
	(*SkillCategory)(nil),         // 9: api.parser.v1.SkillCategory
	(*SkillItem)(nil),             // 10: api.parser.v1.SkillItem
	(*ParseMetadata)(nil),         // 11: api.parser.v1.ParseMetadata
	(*GetParseStatusRequest)(nil), // 12: api.parser.v1.GetParseStatusRequest
	(*GetParseStatusReply)(nil),   // 13: api.parser.v1.GetParseStatusReply
	(*HealthRequest)(nil),         // 14: api.parser.v1.HealthRequest
	(*HealthReply)(nil),           // 15: api.parser.v1.HealthReply
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_backend_services_parser_service_api_parser_v1_parser_proto_depIdxs = []int32{
	1,  // 0: api.parser.v1.ParseDocumentRequest.options:type_name -> api.parser.v1.ParseOptions
	3,  // 1: api.parser.v1.ParseDocumentReply.content:type_name -> api.parser.v1.ParsedContent
	16, // 2: api.parser.v1.ParseDocumentReply.created_at:type_name -> google.protobuf.Timestamp
	4,  // 3: api.parser.v1.ParsedContent.personal_info:type_name -> api.parser.v1.PersonalInfo
	5,  // 4: api.parser.v1.ParsedContent.education:type_name -> api.parser.v1.Education
	6,  // 5: api.parser.v1.ParsedContent.experience:type_name -> api.parser.v1.Experience
	7,  // 6: api.parser.v1.ParsedContent.projects:type_name -> api.parser.v1.Project
	8,  // 7: api.parser.v1.ParsedContent.skills:type_name -> api.parser.v1.Skills
	11, // 8: api.parser.v1.ParsedContent.metadata:type_name -> api.parser.v1.ParseMetadata
	9,  // 9: api.parser.v1.Skills.categories:type_name -> api.parser.v1.SkillCategory
	10, // 10: api.parser.v1.SkillCategory.skills:type_name -> api.parser.v1.SkillItem
	3,  // 11: api.parser.v1.GetParseStatusReply.content:type_name -> api.parser.v1.ParsedContent
	16, // 12: api.parser.v1.GetParseStatusReply.created_at:type_name -> google.protobuf.Timestamp
	16, // 13: api.parser.v1.GetParseStatusReply.updated_at:type_name -> google.protobuf.Timestamp
	16, // 14: api.parser.v1.HealthReply.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 15: api.parser.v1.ParserService.ParseDocument:input_type -> api.parser.v1.ParseDocumentRequest
	12, // 16: api.parser.v1.ParserService.GetParseStatus:input_type -> api.parser.v1.GetParseStatusRequest
	14, // 17: api.parser.v1.ParserService.Health:input_type -> api.parser.v1.HealthRequest
	2,  // 18: api.parser.v1.ParserService.ParseDocument:output_type -> api.parser.v1.ParseDocumentReply
	13, // 19: api.parser.v1.ParserService.GetParseStatus:output_type -> api.parser.v1.GetParseStatusReply
	15, // 20: api.parser.v1.ParserService.Health:output_type -> api.parser.v1.HealthReply
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_backend_services_parser_service_api_parser_v1_parser_proto_init() }
func file_backend_services_parser_service_api_parser_v1_parser_proto_init() {
	if File_backend_services_parser_service_api_parser_v1_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_services_parser_service_api_parser_v1_parser_proto_rawDesc), len(file_backend_services_parser_service_api_parser_v1_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_services_parser_service_api_parser_v1_parser_proto_goTypes,
		DependencyIndexes: file_backend_services_parser_service_api_parser_v1_parser_proto_depIdxs,
		MessageInfos:      file_backend_services_parser_service_api_parser_v1_parser_proto_msgTypes,
	}.Build()
	File_backend_services_parser_service_api_parser_v1_parser_proto = out.File
	file_backend_services_parser_service_api_parser_v1_parser_proto_goTypes = nil
	file_backend_services_parser_service_api_parser_v1_parser_proto_depIdxs = nil
}
