// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.27.3
// source: ai/v1/ai.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分析简历请求
type AnalyzeResumeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResumeId       string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`                   // 简历ID
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                     // 简历内容
	FileType       string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`                   // 文件类型
	TargetPosition string                 `protobuf:"bytes,4,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"` // 目标职位
	Options        *AnalysisOptions       `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`                                     // 分析选项
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeResumeRequest) Reset() {
	*x = AnalyzeResumeRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResumeRequest) ProtoMessage() {}

func (x *AnalyzeResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResumeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeResumeRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeResumeRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *AnalyzeResumeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnalyzeResumeRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *AnalyzeResumeRequest) GetTargetPosition() string {
	if x != nil {
		return x.TargetPosition
	}
	return ""
}

func (x *AnalyzeResumeRequest) GetOptions() *AnalysisOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// 分析选项
type AnalysisOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnableCompleteness   bool                   `protobuf:"varint,1,opt,name=enable_completeness,json=enableCompleteness,proto3" json:"enable_completeness,omitempty"`       // 启用完整性分析
	EnableClarity        bool                   `protobuf:"varint,2,opt,name=enable_clarity,json=enableClarity,proto3" json:"enable_clarity,omitempty"`                      // 启用清晰度分析
	EnableKeyword        bool                   `protobuf:"varint,3,opt,name=enable_keyword,json=enableKeyword,proto3" json:"enable_keyword,omitempty"`                      // 启用关键词分析
	EnableFormat         bool                   `protobuf:"varint,4,opt,name=enable_format,json=enableFormat,proto3" json:"enable_format,omitempty"`                         // 启用格式分析
	EnableQuantification bool                   `protobuf:"varint,5,opt,name=enable_quantification,json=enableQuantification,proto3" json:"enable_quantification,omitempty"` // 启用量化分析
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AnalysisOptions) Reset() {
	*x = AnalysisOptions{}
	mi := &file_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisOptions) ProtoMessage() {}

func (x *AnalysisOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisOptions.ProtoReflect.Descriptor instead.
func (*AnalysisOptions) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisOptions) GetEnableCompleteness() bool {
	if x != nil {
		return x.EnableCompleteness
	}
	return false
}

func (x *AnalysisOptions) GetEnableClarity() bool {
	if x != nil {
		return x.EnableClarity
	}
	return false
}

func (x *AnalysisOptions) GetEnableKeyword() bool {
	if x != nil {
		return x.EnableKeyword
	}
	return false
}

func (x *AnalysisOptions) GetEnableFormat() bool {
	if x != nil {
		return x.EnableFormat
	}
	return false
}

func (x *AnalysisOptions) GetEnableQuantification() bool {
	if x != nil {
		return x.EnableQuantification
	}
	return false
}

// 分析简历响应
type AnalyzeResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"` // 分析ID
	Result        *AnalysisResult        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                           // 分析结果
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // 状态
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                         // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResumeResponse) Reset() {
	*x = AnalyzeResumeResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResumeResponse) ProtoMessage() {}

func (x *AnalyzeResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResumeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResumeResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResumeResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *AnalyzeResumeResponse) GetResult() *AnalysisResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AnalyzeResumeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalyzeResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 分析结果
type AnalysisResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      map[string]*Section    `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 简历章节
	Suggestions   []*Suggestion          `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`                                                                     // 建议列表
	Scores        *ScoreBreakdown        `protobuf:"bytes,3,opt,name=scores,proto3" json:"scores,omitempty"`                                                                               // 评分详情
	Improvements  []*Improvement         `protobuf:"bytes,4,rep,name=improvements,proto3" json:"improvements,omitempty"`                                                                   // 改进建议
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`                                                                             // 总结
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_ai_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisResult) GetSections() map[string]*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *AnalysisResult) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AnalysisResult) GetScores() *ScoreBreakdown {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *AnalysisResult) GetImprovements() []*Improvement {
	if x != nil {
		return x.Improvements
	}
	return nil
}

func (x *AnalysisResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// 简历章节
type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                  // 章节内容
	ExtractedInfo string                 `protobuf:"bytes,2,opt,name=extracted_info,json=extractedInfo,proto3" json:"extracted_info,omitempty"` // 提取的信息
	QualityScore  float32                `protobuf:"fixed32,3,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`  // 质量评分
	Issues        []*Issue               `protobuf:"bytes,4,rep,name=issues,proto3" json:"issues,omitempty"`                                    // 问题列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_ai_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *Section) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Section) GetExtractedInfo() string {
	if x != nil {
		return x.ExtractedInfo
	}
	return ""
}

func (x *Section) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *Section) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

// 问题
type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`               // 问题类型
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 问题描述
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`       // 严重程度
	Suggestion    string                 `protobuf:"bytes,4,opt,name=suggestion,proto3" json:"suggestion,omitempty"`   // 建议
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_ai_v1_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{5}
}

func (x *Issue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Issue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Issue) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

// 建议
type Suggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // 建议ID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`               // 建议类型
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`             // 建议标题
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // 建议描述
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`       // 优先级
	Section       string                 `protobuf:"bytes,6,opt,name=section,proto3" json:"section,omitempty"`         // 相关章节
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`           // 建议操作
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_ai_v1_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{6}
}

func (x *Suggestion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Suggestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Suggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Suggestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Suggestion) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Suggestion) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Suggestion) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 评分详情
type ScoreBreakdown struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OverallScore        float32                `protobuf:"fixed32,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`                                                                                    // 总体评分
	CompletenessScore   float32                `protobuf:"fixed32,2,opt,name=completeness_score,json=completenessScore,proto3" json:"completeness_score,omitempty"`                                                                     // 完整性评分
	ClarityScore        float32                `protobuf:"fixed32,3,opt,name=clarity_score,json=clarityScore,proto3" json:"clarity_score,omitempty"`                                                                                    // 清晰度评分
	KeywordScore        float32                `protobuf:"fixed32,4,opt,name=keyword_score,json=keywordScore,proto3" json:"keyword_score,omitempty"`                                                                                    // 关键词评分
	FormatScore         float32                `protobuf:"fixed32,5,opt,name=format_score,json=formatScore,proto3" json:"format_score,omitempty"`                                                                                       // 格式评分
	QuantificationScore float32                `protobuf:"fixed32,6,opt,name=quantification_score,json=quantificationScore,proto3" json:"quantification_score,omitempty"`                                                               // 量化评分
	DimensionScores     map[string]float32     `protobuf:"bytes,7,rep,name=dimension_scores,json=dimensionScores,proto3" json:"dimension_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // 维度评分
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScoreBreakdown) Reset() {
	*x = ScoreBreakdown{}
	mi := &file_ai_v1_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBreakdown) ProtoMessage() {}

func (x *ScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBreakdown.ProtoReflect.Descriptor instead.
func (*ScoreBreakdown) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{7}
}

func (x *ScoreBreakdown) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *ScoreBreakdown) GetCompletenessScore() float32 {
	if x != nil {
		return x.CompletenessScore
	}
	return 0
}

func (x *ScoreBreakdown) GetClarityScore() float32 {
	if x != nil {
		return x.ClarityScore
	}
	return 0
}

func (x *ScoreBreakdown) GetKeywordScore() float32 {
	if x != nil {
		return x.KeywordScore
	}
	return 0
}

func (x *ScoreBreakdown) GetFormatScore() float32 {
	if x != nil {
		return x.FormatScore
	}
	return 0
}

func (x *ScoreBreakdown) GetQuantificationScore() float32 {
	if x != nil {
		return x.QuantificationScore
	}
	return 0
}

func (x *ScoreBreakdown) GetDimensionScores() map[string]float32 {
	if x != nil {
		return x.DimensionScores
	}
	return nil
}

// 改进建议
type Improvement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`               // 改进类型
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 改进描述
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`       // 优先级
	Section       string                 `protobuf:"bytes,4,opt,name=section,proto3" json:"section,omitempty"`         // 相关章节
	Before        string                 `protobuf:"bytes,5,opt,name=before,proto3" json:"before,omitempty"`           // 修改前
	After         string                 `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`             // 修改后
	Examples      []string               `protobuf:"bytes,7,rep,name=examples,proto3" json:"examples,omitempty"`       // 示例
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Improvement) Reset() {
	*x = Improvement{}
	mi := &file_ai_v1_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Improvement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Improvement) ProtoMessage() {}

func (x *Improvement) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Improvement.ProtoReflect.Descriptor instead.
func (*Improvement) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{8}
}

func (x *Improvement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Improvement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Improvement) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Improvement) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Improvement) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *Improvement) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *Improvement) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

// 生成建议请求
type GenerateSuggestionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId     string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`             // 分析ID
	AnalysisResult *AnalysisResult        `protobuf:"bytes,2,opt,name=analysis_result,json=analysisResult,proto3" json:"analysis_result,omitempty"` // 分析结果
	TargetPosition string                 `protobuf:"bytes,3,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"` // 目标职位
	Industry       string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`                                   // 行业
	Options        *SuggestionOptions     `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`                                     // 建议选项
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateSuggestionsRequest) Reset() {
	*x = GenerateSuggestionsRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSuggestionsRequest) ProtoMessage() {}

func (x *GenerateSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateSuggestionsRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *GenerateSuggestionsRequest) GetAnalysisResult() *AnalysisResult {
	if x != nil {
		return x.AnalysisResult
	}
	return nil
}

func (x *GenerateSuggestionsRequest) GetTargetPosition() string {
	if x != nil {
		return x.TargetPosition
	}
	return ""
}

func (x *GenerateSuggestionsRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *GenerateSuggestionsRequest) GetOptions() *SuggestionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// 建议选项
type SuggestionOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxSuggestions  int32                  `protobuf:"varint,1,opt,name=max_suggestions,json=maxSuggestions,proto3" json:"max_suggestions,omitempty"`   // 最大建议数
	FocusArea       string                 `protobuf:"bytes,2,opt,name=focus_area,json=focusArea,proto3" json:"focus_area,omitempty"`                   // 重点领域
	ExperienceLevel string                 `protobuf:"bytes,3,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"` // 经验级别
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SuggestionOptions) Reset() {
	*x = SuggestionOptions{}
	mi := &file_ai_v1_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionOptions) ProtoMessage() {}

func (x *SuggestionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionOptions.ProtoReflect.Descriptor instead.
func (*SuggestionOptions) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{10}
}

func (x *SuggestionOptions) GetMaxSuggestions() int32 {
	if x != nil {
		return x.MaxSuggestions
	}
	return 0
}

func (x *SuggestionOptions) GetFocusArea() string {
	if x != nil {
		return x.FocusArea
	}
	return ""
}

func (x *SuggestionOptions) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

// 生成建议响应
type GenerateSuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []*Suggestion          `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"` // 建议列表
	Reasoning     string                 `protobuf:"bytes,2,opt,name=reasoning,proto3" json:"reasoning,omitempty"`     // 推理过程
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`           // 状态
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`         // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSuggestionsResponse) Reset() {
	*x = GenerateSuggestionsResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSuggestionsResponse) ProtoMessage() {}

func (x *GenerateSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateSuggestionsResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *GenerateSuggestionsResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *GenerateSuggestionsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateSuggestionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 智能问答请求
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 用户消息
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                      // 上下文
	Options       *ChatOptions           `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`                      // 聊天选项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{12}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ChatRequest) GetOptions() *ChatOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// 聊天选项
type ChatOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UseResumeContext bool                   `protobuf:"varint,1,opt,name=use_resume_context,json=useResumeContext,proto3" json:"use_resume_context,omitempty"` // 使用简历上下文
	UseKnowledgeBase bool                   `protobuf:"varint,2,opt,name=use_knowledge_base,json=useKnowledgeBase,proto3" json:"use_knowledge_base,omitempty"` // 使用知识库
	Language         string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                                            // 语言
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatOptions) Reset() {
	*x = ChatOptions{}
	mi := &file_ai_v1_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatOptions) ProtoMessage() {}

func (x *ChatOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatOptions.ProtoReflect.Descriptor instead.
func (*ChatOptions) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{13}
}

func (x *ChatOptions) GetUseResumeContext() bool {
	if x != nil {
		return x.UseResumeContext
	}
	return false
}

func (x *ChatOptions) GetUseKnowledgeBase() bool {
	if x != nil {
		return x.UseKnowledgeBase
	}
	return false
}

func (x *ChatOptions) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// 智能问答响应
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`                    // AI回复
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Sources       []string               `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`                      // 信息来源
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                        // 状态
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                      // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{14}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 知识检索请求
type RetrieveKnowledgeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Query               string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                                          // 查询内容
	TopK                int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                                               // 返回数量
	SimilarityThreshold float32                `protobuf:"fixed32,3,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"` // 相似度阈值
	Filters             []string               `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`                                                      // 过滤条件
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RetrieveKnowledgeRequest) Reset() {
	*x = RetrieveKnowledgeRequest{}
	mi := &file_ai_v1_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveKnowledgeRequest) ProtoMessage() {}

func (x *RetrieveKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*RetrieveKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{15}
}

func (x *RetrieveKnowledgeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveKnowledgeRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveKnowledgeRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *RetrieveKnowledgeRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// 知识检索响应
type RetrieveKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`     // 知识条目
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // 状态
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveKnowledgeResponse) Reset() {
	*x = RetrieveKnowledgeResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveKnowledgeResponse) ProtoMessage() {}

func (x *RetrieveKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*RetrieveKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{16}
}

func (x *RetrieveKnowledgeResponse) GetItems() []*KnowledgeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RetrieveKnowledgeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RetrieveKnowledgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 知识条目
type KnowledgeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 条目ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                                                                 // 标题
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 内容
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`                                                                               // 相关性评分
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeItem) Reset() {
	*x = KnowledgeItem{}
	mi := &file_ai_v1_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeItem) ProtoMessage() {}

func (x *KnowledgeItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeItem.ProtoReflect.Descriptor instead.
func (*KnowledgeItem) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{17}
}

func (x *KnowledgeItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *KnowledgeItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                                   // 状态
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                                                 // 版本
	Components    map[string]string      `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 组件状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_ai_v1_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_ai_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_ai_v1_ai_proto protoreflect.FileDescriptor

const file_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eai/v1/ai.proto\x12\x05ai.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc5\x01\n" +
	"\x14AnalyzeResumeRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12'\n" +
	"\x0ftarget_position\x18\x04 \x01(\tR\x0etargetPosition\x120\n" +
	"\aoptions\x18\x05 \x01(\v2\x16.ai.v1.AnalysisOptionsR\aoptions\"\xea\x01\n" +
	"\x0fAnalysisOptions\x12/\n" +
	"\x13enable_completeness\x18\x01 \x01(\bR\x12enableCompleteness\x12%\n" +
	"\x0eenable_clarity\x18\x02 \x01(\bR\renableClarity\x12%\n" +
	"\x0eenable_keyword\x18\x03 \x01(\bR\renableKeyword\x12#\n" +
	"\renable_format\x18\x04 \x01(\bR\fenableFormat\x123\n" +
	"\x15enable_quantification\x18\x05 \x01(\bR\x14enableQuantification\"\x99\x01\n" +
	"\x15AnalyzeResumeResponse\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.ai.v1.AnalysisResultR\x06result\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xd4\x02\n" +
	"\x0eAnalysisResult\x12?\n" +
	"\bsections\x18\x01 \x03(\v2#.ai.v1.AnalysisResult.SectionsEntryR\bsections\x123\n" +
	"\vsuggestions\x18\x02 \x03(\v2\x11.ai.v1.SuggestionR\vsuggestions\x12-\n" +
	"\x06scores\x18\x03 \x01(\v2\x15.ai.v1.ScoreBreakdownR\x06scores\x126\n" +
	"\fimprovements\x18\x04 \x03(\v2\x12.ai.v1.ImprovementR\fimprovements\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x1aK\n" +
	"\rSectionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.ai.v1.SectionR\x05value:\x028\x01\"\x95\x01\n" +
	"\aSection\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12%\n" +
	"\x0eextracted_info\x18\x02 \x01(\tR\rextractedInfo\x12#\n" +
	"\rquality_score\x18\x03 \x01(\x02R\fqualityScore\x12$\n" +
	"\x06issues\x18\x04 \x03(\v2\f.ai.v1.IssueR\x06issues\"y\n" +
	"\x05Issue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x04 \x01(\tR\n" +
	"suggestion\"\xb6\x01\n" +
	"\n" +
	"Suggestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x18\n" +
	"\asection\x18\x06 \x01(\tR\asection\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\"\x9f\x03\n" +
	"\x0eScoreBreakdown\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x02R\foverallScore\x12-\n" +
	"\x12completeness_score\x18\x02 \x01(\x02R\x11completenessScore\x12#\n" +
	"\rclarity_score\x18\x03 \x01(\x02R\fclarityScore\x12#\n" +
	"\rkeyword_score\x18\x04 \x01(\x02R\fkeywordScore\x12!\n" +
	"\fformat_score\x18\x05 \x01(\x02R\vformatScore\x121\n" +
	"\x14quantification_score\x18\x06 \x01(\x02R\x13quantificationScore\x12U\n" +
	"\x10dimension_scores\x18\a \x03(\v2*.ai.v1.ScoreBreakdown.DimensionScoresEntryR\x0fdimensionScores\x1aB\n" +
	"\x14DimensionScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xc3\x01\n" +
	"\vImprovement\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x18\n" +
	"\asection\x18\x04 \x01(\tR\asection\x12\x16\n" +
	"\x06before\x18\x05 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x06 \x01(\tR\x05after\x12\x1a\n" +
	"\bexamples\x18\a \x03(\tR\bexamples\"\xf6\x01\n" +
	"\x1aGenerateSuggestionsRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12>\n" +
	"\x0fanalysis_result\x18\x02 \x01(\v2\x15.ai.v1.AnalysisResultR\x0eanalysisResult\x12'\n" +
	"\x0ftarget_position\x18\x03 \x01(\tR\x0etargetPosition\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x122\n" +
	"\aoptions\x18\x05 \x01(\v2\x18.ai.v1.SuggestionOptionsR\aoptions\"\x86\x01\n" +
	"\x11SuggestionOptions\x12'\n" +
	"\x0fmax_suggestions\x18\x01 \x01(\x05R\x0emaxSuggestions\x12\x1d\n" +
	"\n" +
	"focus_area\x18\x02 \x01(\tR\tfocusArea\x12)\n" +
	"\x10experience_level\x18\x03 \x01(\tR\x0fexperienceLevel\"\xa2\x01\n" +
	"\x1bGenerateSuggestionsResponse\x123\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x11.ai.v1.SuggestionR\vsuggestions\x12\x1c\n" +
	"\treasoning\x18\x02 \x01(\tR\treasoning\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x8e\x01\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12,\n" +
	"\aoptions\x18\x04 \x01(\v2\x12.ai.v1.ChatOptionsR\aoptions\"\x85\x01\n" +
	"\vChatOptions\x12,\n" +
	"\x12use_resume_context\x18\x01 \x01(\bR\x10useResumeContext\x12,\n" +
	"\x12use_knowledge_base\x18\x02 \x01(\bR\x10useKnowledgeBase\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\x95\x01\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\asources\x18\x03 \x03(\tR\asources\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x92\x01\n" +
	"\x18RetrieveKnowledgeRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x121\n" +
	"\x14similarity_threshold\x18\x03 \x01(\x02R\x13similarityThreshold\x12\x18\n" +
	"\afilters\x18\x04 \x03(\tR\afilters\"y\n" +
	"\x19RetrieveKnowledgeResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.ai.v1.KnowledgeItemR\x05items\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe2\x01\n" +
	"\rKnowledgeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".ai.v1.KnowledgeItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12E\n" +
	"\n" +
	"components\x18\x03 \x03(\v2%.ai.v1.HealthResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9b\x04\n" +
	"\tAIService\x12i\n" +
	"\rAnalyzeResume\x12\x1b.ai.v1.AnalyzeResumeRequest\x1a\x1c.ai.v1.AnalyzeResumeResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/ai/analyze\x12\x7f\n" +
	"\x13GenerateSuggestions\x12!.ai.v1.GenerateSuggestionsRequest\x1a\".ai.v1.GenerateSuggestionsResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/ai/suggestions\x12K\n" +
	"\x04Chat\x12\x12.ai.v1.ChatRequest\x1a\x13.ai.v1.ChatResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/ai/chat\x12\x80\x01\n" +
	"\x11RetrieveKnowledge\x12\x1f.ai.v1.RetrieveKnowledgeRequest\x1a .ai.v1.RetrieveKnowledgeResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/ai/knowledge/retrieve\x12R\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x15.ai.v1.HealthResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/ai/healthBQZOgithub.com/lyb88999/resume_helper/backend/services/ai-service/api/ai/v1;v1b\x06proto3"

var (
	file_ai_v1_ai_proto_rawDescOnce sync.Once
	file_ai_v1_ai_proto_rawDescData []byte
)

func file_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_ai_proto_rawDesc), len(file_ai_v1_ai_proto_rawDesc)))
	})
	return file_ai_v1_ai_proto_rawDescData
}

var file_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ai_v1_ai_proto_goTypes = []any{
	(*AnalyzeResumeRequest)(nil),        // 0: ai.v1.AnalyzeResumeRequest
	(*AnalysisOptions)(nil),             // 1: ai.v1.AnalysisOptions
	(*AnalyzeResumeResponse)(nil),       // 2: ai.v1.AnalyzeResumeResponse
	(*AnalysisResult)(nil),              // 3: ai.v1.AnalysisResult
	(*Section)(nil),                     // 4: ai.v1.Section
	(*Issue)(nil),                       // 5: ai.v1.Issue
	(*Suggestion)(nil),                  // 6: ai.v1.Suggestion
	(*ScoreBreakdown)(nil),              // 7: ai.v1.ScoreBreakdown
	(*Improvement)(nil),                 // 8: ai.v1.Improvement
	(*GenerateSuggestionsRequest)(nil),  // 9: ai.v1.GenerateSuggestionsRequest
	(*SuggestionOptions)(nil),           // 10: ai.v1.SuggestionOptions
	(*GenerateSuggestionsResponse)(nil), // 11: ai.v1.GenerateSuggestionsResponse
	(*ChatRequest)(nil),                 // 12: ai.v1.ChatRequest
	(*ChatOptions)(nil),                 // 13: ai.v1.ChatOptions
	(*ChatResponse)(nil),                // 14: ai.v1.ChatResponse
	(*RetrieveKnowledgeRequest)(nil),    // 15: ai.v1.RetrieveKnowledgeRequest
	(*RetrieveKnowledgeResponse)(nil),   // 16: ai.v1.RetrieveKnowledgeResponse
	(*KnowledgeItem)(nil),               // 17: ai.v1.KnowledgeItem
	(*HealthResponse)(nil),              // 18: ai.v1.HealthResponse
	nil,                                 // 19: ai.v1.AnalysisResult.SectionsEntry
	nil,                                 // 20: ai.v1.ScoreBreakdown.DimensionScoresEntry
	nil,                                 // 21: ai.v1.KnowledgeItem.MetadataEntry
	nil,                                 // 22: ai.v1.HealthResponse.ComponentsEntry
	(*emptypb.Empty)(nil),               // 23: google.protobuf.Empty
}
var file_ai_v1_ai_proto_depIdxs = []int32{
	1,  // 0: ai.v1.AnalyzeResumeRequest.options:type_name -> ai.v1.AnalysisOptions
	3,  // 1: ai.v1.AnalyzeResumeResponse.result:type_name -> ai.v1.AnalysisResult
	19, // 2: ai.v1.AnalysisResult.sections:type_name -> ai.v1.AnalysisResult.SectionsEntry
	6,  // 3: ai.v1.AnalysisResult.suggestions:type_name -> ai.v1.Suggestion
	7,  // 4: ai.v1.AnalysisResult.scores:type_name -> ai.v1.ScoreBreakdown
	8,  // 5: ai.v1.AnalysisResult.improvements:type_name -> ai.v1.Improvement
	5,  // 6: ai.v1.Section.issues:type_name -> ai.v1.Issue
	20, // 7: ai.v1.ScoreBreakdown.dimension_scores:type_name -> ai.v1.ScoreBreakdown.DimensionScoresEntry
	3,  // 8: ai.v1.GenerateSuggestionsRequest.analysis_result:type_name -> ai.v1.AnalysisResult
	10, // 9: ai.v1.GenerateSuggestionsRequest.options:type_name -> ai.v1.SuggestionOptions
	6,  // 10: ai.v1.GenerateSuggestionsResponse.suggestions:type_name -> ai.v1.Suggestion
	13, // 11: ai.v1.ChatRequest.options:type_name -> ai.v1.ChatOptions
	17, // 12: ai.v1.RetrieveKnowledgeResponse.items:type_name -> ai.v1.KnowledgeItem
	21, // 13: ai.v1.KnowledgeItem.metadata:type_name -> ai.v1.KnowledgeItem.MetadataEntry
	22, // 14: ai.v1.HealthResponse.components:type_name -> ai.v1.HealthResponse.ComponentsEntry
	4,  // 15: ai.v1.AnalysisResult.SectionsEntry.value:type_name -> ai.v1.Section
	0,  // 16: ai.v1.AIService.AnalyzeResume:input_type -> ai.v1.AnalyzeResumeRequest
	9,  // 17: ai.v1.AIService.GenerateSuggestions:input_type -> ai.v1.GenerateSuggestionsRequest
	12, // 18: ai.v1.AIService.Chat:input_type -> ai.v1.ChatRequest
	15, // 19: ai.v1.AIService.RetrieveKnowledge:input_type -> ai.v1.RetrieveKnowledgeRequest
	23, // 20: ai.v1.AIService.Health:input_type -> google.protobuf.Empty
	2,  // 21: ai.v1.AIService.AnalyzeResume:output_type -> ai.v1.AnalyzeResumeResponse
	11, // 22: ai.v1.AIService.GenerateSuggestions:output_type -> ai.v1.GenerateSuggestionsResponse
	14, // 23: ai.v1.AIService.Chat:output_type -> ai.v1.ChatResponse
	16, // 24: ai.v1.AIService.RetrieveKnowledge:output_type -> ai.v1.RetrieveKnowledgeResponse
	18, // 25: ai.v1.AIService.Health:output_type -> ai.v1.HealthResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ai_v1_ai_proto_init() }
func file_ai_v1_ai_proto_init() {
	if File_ai_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_ai_proto_rawDesc), len(file_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_ai_v1_ai_proto = out.File
	file_ai_v1_ai_proto_goTypes = nil
	file_ai_v1_ai_proto_depIdxs = nil
}
