// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.27.3
// source: backend/shared/proto/resume/resume.proto

package resume

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传简历请求
type UploadResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,4,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeRequest) Reset() {
	*x = UploadResumeRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeRequest) ProtoMessage() {}

func (x *UploadResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeRequest.ProtoReflect.Descriptor instead.
func (*UploadResumeRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{0}
}

func (x *UploadResumeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadResumeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadResumeRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadResumeRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadResumeRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

// 上传简历响应
type UploadResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Resume        *Resume                `protobuf:"bytes,3,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeResponse) Reset() {
	*x = UploadResumeResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeResponse) ProtoMessage() {}

func (x *UploadResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeResponse.ProtoReflect.Descriptor instead.
func (*UploadResumeResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResumeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// 解析简历请求
type ParseResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      uint64                 `protobuf:"varint,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResumeRequest) Reset() {
	*x = ParseResumeRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResumeRequest) ProtoMessage() {}

func (x *ParseResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResumeRequest.ProtoReflect.Descriptor instead.
func (*ParseResumeRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{2}
}

func (x *ParseResumeRequest) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

// 解析简历响应
type ParseResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResumeResponse) Reset() {
	*x = ParseResumeResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResumeResponse) ProtoMessage() {}

func (x *ParseResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResumeResponse.ProtoReflect.Descriptor instead.
func (*ParseResumeResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{3}
}

func (x *ParseResumeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ParseResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseResumeResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 获取解析结果请求
type GetParseResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      uint64                 `protobuf:"varint,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParseResultRequest) Reset() {
	*x = GetParseResultRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParseResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParseResultRequest) ProtoMessage() {}

func (x *GetParseResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParseResultRequest.ProtoReflect.Descriptor instead.
func (*GetParseResultRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{4}
}

func (x *GetParseResultRequest) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

// 获取解析结果响应
type GetParseResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Resume        *Resume                `protobuf:"bytes,3,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParseResultResponse) Reset() {
	*x = GetParseResultResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParseResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParseResultResponse) ProtoMessage() {}

func (x *GetParseResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParseResultResponse.ProtoReflect.Descriptor instead.
func (*GetParseResultResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{5}
}

func (x *GetParseResultResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetParseResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetParseResultResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// 获取简历列表请求
type ListResumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesRequest) Reset() {
	*x = ListResumesRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesRequest) ProtoMessage() {}

func (x *ListResumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesRequest.ProtoReflect.Descriptor instead.
func (*ListResumesRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{6}
}

func (x *ListResumesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListResumesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResumesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取简历列表响应
type ListResumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Resumes       []*Resume              `protobuf:"bytes,3,rep,name=resumes,proto3" json:"resumes,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesResponse) Reset() {
	*x = ListResumesResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesResponse) ProtoMessage() {}

func (x *ListResumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesResponse.ProtoReflect.Descriptor instead.
func (*ListResumesResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{7}
}

func (x *ListResumesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListResumesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListResumesResponse) GetResumes() []*Resume {
	if x != nil {
		return x.Resumes
	}
	return nil
}

func (x *ListResumesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 删除简历请求
type DeleteResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      uint64                 `protobuf:"varint,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResumeRequest) Reset() {
	*x = DeleteResumeRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeRequest) ProtoMessage() {}

func (x *DeleteResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteResumeRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResumeRequest) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

func (x *DeleteResumeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 删除简历响应
type DeleteResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResumeResponse) Reset() {
	*x = DeleteResumeResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeResponse) ProtoMessage() {}

func (x *DeleteResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteResumeResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResumeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 分析简历请求
type AnalyzeResumeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResumeId       uint64                 `protobuf:"varint,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	TargetPosition string                 `protobuf:"bytes,2,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	Industry       string                 `protobuf:"bytes,3,opt,name=industry,proto3" json:"industry,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeResumeRequest) Reset() {
	*x = AnalyzeResumeRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResumeRequest) ProtoMessage() {}

func (x *AnalyzeResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResumeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeResumeRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeResumeRequest) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

func (x *AnalyzeResumeRequest) GetTargetPosition() string {
	if x != nil {
		return x.TargetPosition
	}
	return ""
}

func (x *AnalyzeResumeRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

// 分析简历响应
type AnalyzeResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AnalysisId    string                 `protobuf:"bytes,3,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResumeResponse) Reset() {
	*x = AnalyzeResumeResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResumeResponse) ProtoMessage() {}

func (x *AnalyzeResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResumeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResumeResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{11}
}

func (x *AnalyzeResumeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AnalyzeResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnalyzeResumeResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

// 生成建议请求
type GenerateSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    uint64                 `protobuf:"varint,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSuggestionsRequest) Reset() {
	*x = GenerateSuggestionsRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSuggestionsRequest) ProtoMessage() {}

func (x *GenerateSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateSuggestionsRequest) GetAnalysisId() uint64 {
	if x != nil {
		return x.AnalysisId
	}
	return 0
}

// 生成建议响应
type GenerateSuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Suggestions   []*Suggestion          `protobuf:"bytes,3,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSuggestionsResponse) Reset() {
	*x = GenerateSuggestionsResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSuggestionsResponse) ProtoMessage() {}

func (x *GenerateSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateSuggestionsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateSuggestionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateSuggestionsResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

// 获取分析结果请求
type GetAnalysisResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    uint64                 `protobuf:"varint,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisResultRequest) Reset() {
	*x = GetAnalysisResultRequest{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisResultRequest) ProtoMessage() {}

func (x *GetAnalysisResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisResultRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisResultRequest) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{14}
}

func (x *GetAnalysisResultRequest) GetAnalysisId() uint64 {
	if x != nil {
		return x.AnalysisId
	}
	return 0
}

// 获取分析结果响应
type GetAnalysisResultResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AnalysisResult *AnalysisResult        `protobuf:"bytes,3,opt,name=analysis_result,json=analysisResult,proto3" json:"analysis_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAnalysisResultResponse) Reset() {
	*x = GetAnalysisResultResponse{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisResultResponse) ProtoMessage() {}

func (x *GetAnalysisResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisResultResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisResultResponse) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{15}
}

func (x *GetAnalysisResultResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAnalysisResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAnalysisResultResponse) GetAnalysisResult() *AnalysisResult {
	if x != nil {
		return x.AnalysisResult
	}
	return nil
}

// 简历信息
type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ParsedContent *structpb.Struct       `protobuf:"bytes,7,opt,name=parsed_content,json=parsedContent,proto3" json:"parsed_content,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{16}
}

func (x *Resume) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resume) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Resume) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Resume) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Resume) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Resume) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Resume) GetParsedContent() *structpb.Struct {
	if x != nil {
		return x.ParsedContent
	}
	return nil
}

func (x *Resume) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Resume) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resume) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 分析结果
type AnalysisResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResumeId            uint64                 `protobuf:"varint,2,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	OverallScore        float64                `protobuf:"fixed64,3,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	CompletenessScore   float64                `protobuf:"fixed64,4,opt,name=completeness_score,json=completenessScore,proto3" json:"completeness_score,omitempty"`
	ClarityScore        float64                `protobuf:"fixed64,5,opt,name=clarity_score,json=clarityScore,proto3" json:"clarity_score,omitempty"`
	KeywordScore        float64                `protobuf:"fixed64,6,opt,name=keyword_score,json=keywordScore,proto3" json:"keyword_score,omitempty"`
	FormatScore         float64                `protobuf:"fixed64,7,opt,name=format_score,json=formatScore,proto3" json:"format_score,omitempty"`
	QuantificationScore float64                `protobuf:"fixed64,8,opt,name=quantification_score,json=quantificationScore,proto3" json:"quantification_score,omitempty"`
	Suggestions         []*Suggestion          `protobuf:"bytes,9,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	AnalysisVersion     string                 `protobuf:"bytes,10,opt,name=analysis_version,json=analysisVersion,proto3" json:"analysis_version,omitempty"`
	TargetPosition      string                 `protobuf:"bytes,11,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	Industry            string                 `protobuf:"bytes,12,opt,name=industry,proto3" json:"industry,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{17}
}

func (x *AnalysisResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnalysisResult) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

func (x *AnalysisResult) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *AnalysisResult) GetCompletenessScore() float64 {
	if x != nil {
		return x.CompletenessScore
	}
	return 0
}

func (x *AnalysisResult) GetClarityScore() float64 {
	if x != nil {
		return x.ClarityScore
	}
	return 0
}

func (x *AnalysisResult) GetKeywordScore() float64 {
	if x != nil {
		return x.KeywordScore
	}
	return 0
}

func (x *AnalysisResult) GetFormatScore() float64 {
	if x != nil {
		return x.FormatScore
	}
	return 0
}

func (x *AnalysisResult) GetQuantificationScore() float64 {
	if x != nil {
		return x.QuantificationScore
	}
	return 0
}

func (x *AnalysisResult) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AnalysisResult) GetAnalysisVersion() string {
	if x != nil {
		return x.AnalysisVersion
	}
	return ""
}

func (x *AnalysisResult) GetTargetPosition() string {
	if x != nil {
		return x.TargetPosition
	}
	return ""
}

func (x *AnalysisResult) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *AnalysisResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 优化建议
type Suggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Examples      []string               `protobuf:"bytes,6,rep,name=examples,proto3" json:"examples,omitempty"`
	Location      *SuggestionLocation    `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{18}
}

func (x *Suggestion) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Suggestion) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Suggestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Suggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Suggestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Suggestion) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Suggestion) GetLocation() *SuggestionLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Suggestion) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// 建议位置
type SuggestionLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionLocation) Reset() {
	*x = SuggestionLocation{}
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionLocation) ProtoMessage() {}

func (x *SuggestionLocation) ProtoReflect() protoreflect.Message {
	mi := &file_backend_shared_proto_resume_resume_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionLocation.ProtoReflect.Descriptor instead.
func (*SuggestionLocation) Descriptor() ([]byte, []int) {
	return file_backend_shared_proto_resume_resume_proto_rawDescGZIP(), []int{19}
}

func (x *SuggestionLocation) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SuggestionLocation) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SuggestionLocation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

var File_backend_shared_proto_resume_resume_proto protoreflect.FileDescriptor

const file_backend_shared_proto_resume_resume_proto_rawDesc = "" +
	"\n" +
	"(backend/shared/proto/resume/resume.proto\x12\tresume.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9b\x01\n" +
	"\x13UploadResumeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_data\x18\x04 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\"o\n" +
	"\x14UploadResumeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06resume\x18\x03 \x01(\v2\x11.resume.v1.ResumeR\x06resume\"1\n" +
	"\x12ParseResumeRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\x04R\bresumeId\"\\\n" +
	"\x13ParseResumeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"4\n" +
	"\x15GetParseResultRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\x04R\bresumeId\"q\n" +
	"\x16GetParseResultResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06resume\x18\x03 \x01(\v2\x11.resume.v1.ResumeR\x06resume\"^\n" +
	"\x12ListResumesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x86\x01\n" +
	"\x13ListResumesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\aresumes\x18\x03 \x03(\v2\x11.resume.v1.ResumeR\aresumes\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"K\n" +
	"\x13DeleteResumeRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\x04R\bresumeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"D\n" +
	"\x14DeleteResumeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\x14AnalyzeResumeRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\x04R\bresumeId\x12'\n" +
	"\x0ftarget_position\x18\x02 \x01(\tR\x0etargetPosition\x12\x1a\n" +
	"\bindustry\x18\x03 \x01(\tR\bindustry\"f\n" +
	"\x15AnalyzeResumeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vanalysis_id\x18\x03 \x01(\tR\n" +
	"analysisId\"=\n" +
	"\x1aGenerateSuggestionsRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\x04R\n" +
	"analysisId\"\x84\x01\n" +
	"\x1bGenerateSuggestionsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\vsuggestions\x18\x03 \x03(\v2\x15.resume.v1.SuggestionR\vsuggestions\";\n" +
	"\x18GetAnalysisResultRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\x04R\n" +
	"analysisId\"\x8d\x01\n" +
	"\x19GetAnalysisResultResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x0fanalysis_result\x18\x03 \x01(\v2\x19.resume.v1.AnalysisResultR\x0eanalysisResult\"\xec\x02\n" +
	"\x06Resume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12>\n" +
	"\x0eparsed_content\x18\a \x01(\v2\x17.google.protobuf.StructR\rparsedContent\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x95\x04\n" +
	"\x0eAnalysisResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tresume_id\x18\x02 \x01(\x04R\bresumeId\x12#\n" +
	"\roverall_score\x18\x03 \x01(\x01R\foverallScore\x12-\n" +
	"\x12completeness_score\x18\x04 \x01(\x01R\x11completenessScore\x12#\n" +
	"\rclarity_score\x18\x05 \x01(\x01R\fclarityScore\x12#\n" +
	"\rkeyword_score\x18\x06 \x01(\x01R\fkeywordScore\x12!\n" +
	"\fformat_score\x18\a \x01(\x01R\vformatScore\x121\n" +
	"\x14quantification_score\x18\b \x01(\x01R\x13quantificationScore\x127\n" +
	"\vsuggestions\x18\t \x03(\v2\x15.resume.v1.SuggestionR\vsuggestions\x12)\n" +
	"\x10analysis_version\x18\n" +
	" \x01(\tR\x0fanalysisVersion\x12'\n" +
	"\x0ftarget_position\x18\v \x01(\tR\x0etargetPosition\x12\x1a\n" +
	"\bindustry\x18\f \x01(\tR\bindustry\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xfb\x01\n" +
	"\n" +
	"Suggestion\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x06 \x03(\tR\bexamples\x129\n" +
	"\blocation\x18\a \x01(\v2\x1d.resume.v1.SuggestionLocationR\blocation\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\"Z\n" +
	"\x12SuggestionLocation\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field2\xaa\x03\n" +
	"\x13ResumeParserService\x12O\n" +
	"\fUploadResume\x12\x1e.resume.v1.UploadResumeRequest\x1a\x1f.resume.v1.UploadResumeResponse\x12L\n" +
	"\vParseResume\x12\x1d.resume.v1.ParseResumeRequest\x1a\x1e.resume.v1.ParseResumeResponse\x12U\n" +
	"\x0eGetParseResult\x12 .resume.v1.GetParseResultRequest\x1a!.resume.v1.GetParseResultResponse\x12L\n" +
	"\vListResumes\x12\x1d.resume.v1.ListResumesRequest\x1a\x1e.resume.v1.ListResumesResponse\x12O\n" +
	"\fDeleteResume\x12\x1e.resume.v1.DeleteResumeRequest\x1a\x1f.resume.v1.DeleteResumeResponse2\xad\x02\n" +
	"\x11AIAnalysisService\x12R\n" +
	"\rAnalyzeResume\x12\x1f.resume.v1.AnalyzeResumeRequest\x1a .resume.v1.AnalyzeResumeResponse\x12d\n" +
	"\x13GenerateSuggestions\x12%.resume.v1.GenerateSuggestionsRequest\x1a&.resume.v1.GenerateSuggestionsResponse\x12^\n" +
	"\x11GetAnalysisResult\x12#.resume.v1.GetAnalysisResultRequest\x1a$.resume.v1.GetAnalysisResultResponseBFZDgithub.com/lyb88999/resume_helper/backend/shared/proto/resume;resumeb\x06proto3"

var (
	file_backend_shared_proto_resume_resume_proto_rawDescOnce sync.Once
	file_backend_shared_proto_resume_resume_proto_rawDescData []byte
)

func file_backend_shared_proto_resume_resume_proto_rawDescGZIP() []byte {
	file_backend_shared_proto_resume_resume_proto_rawDescOnce.Do(func() {
		file_backend_shared_proto_resume_resume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_shared_proto_resume_resume_proto_rawDesc), len(file_backend_shared_proto_resume_resume_proto_rawDesc)))
	})
	return file_backend_shared_proto_resume_resume_proto_rawDescData
}

var file_backend_shared_proto_resume_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_backend_shared_proto_resume_resume_proto_goTypes = []any{
	(*UploadResumeRequest)(nil),         // 0: resume.v1.UploadResumeRequest
	(*UploadResumeResponse)(nil),        // 1: resume.v1.UploadResumeResponse
	(*ParseResumeRequest)(nil),          // 2: resume.v1.ParseResumeRequest
	(*ParseResumeResponse)(nil),         // 3: resume.v1.ParseResumeResponse
	(*GetParseResultRequest)(nil),       // 4: resume.v1.GetParseResultRequest
	(*GetParseResultResponse)(nil),      // 5: resume.v1.GetParseResultResponse
	(*ListResumesRequest)(nil),          // 6: resume.v1.ListResumesRequest
	(*ListResumesResponse)(nil),         // 7: resume.v1.ListResumesResponse
	(*DeleteResumeRequest)(nil),         // 8: resume.v1.DeleteResumeRequest
	(*DeleteResumeResponse)(nil),        // 9: resume.v1.DeleteResumeResponse
	(*AnalyzeResumeRequest)(nil),        // 10: resume.v1.AnalyzeResumeRequest
	(*AnalyzeResumeResponse)(nil),       // 11: resume.v1.AnalyzeResumeResponse
	(*GenerateSuggestionsRequest)(nil),  // 12: resume.v1.GenerateSuggestionsRequest
	(*GenerateSuggestionsResponse)(nil), // 13: resume.v1.GenerateSuggestionsResponse
	(*GetAnalysisResultRequest)(nil),    // 14: resume.v1.GetAnalysisResultRequest
	(*GetAnalysisResultResponse)(nil),   // 15: resume.v1.GetAnalysisResultResponse
	(*Resume)(nil),                      // 16: resume.v1.Resume
	(*AnalysisResult)(nil),              // 17: resume.v1.AnalysisResult
	(*Suggestion)(nil),                  // 18: resume.v1.Suggestion
	(*SuggestionLocation)(nil),          // 19: resume.v1.SuggestionLocation
	(*structpb.Struct)(nil),             // 20: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
}
var file_backend_shared_proto_resume_resume_proto_depIdxs = []int32{
	16, // 0: resume.v1.UploadResumeResponse.resume:type_name -> resume.v1.Resume
	16, // 1: resume.v1.GetParseResultResponse.resume:type_name -> resume.v1.Resume
	16, // 2: resume.v1.ListResumesResponse.resumes:type_name -> resume.v1.Resume
	18, // 3: resume.v1.GenerateSuggestionsResponse.suggestions:type_name -> resume.v1.Suggestion
	17, // 4: resume.v1.GetAnalysisResultResponse.analysis_result:type_name -> resume.v1.AnalysisResult
	20, // 5: resume.v1.Resume.parsed_content:type_name -> google.protobuf.Struct
	21, // 6: resume.v1.Resume.created_at:type_name -> google.protobuf.Timestamp
	21, // 7: resume.v1.Resume.updated_at:type_name -> google.protobuf.Timestamp
	18, // 8: resume.v1.AnalysisResult.suggestions:type_name -> resume.v1.Suggestion
	21, // 9: resume.v1.AnalysisResult.created_at:type_name -> google.protobuf.Timestamp
	19, // 10: resume.v1.Suggestion.location:type_name -> resume.v1.SuggestionLocation
	0,  // 11: resume.v1.ResumeParserService.UploadResume:input_type -> resume.v1.UploadResumeRequest
	2,  // 12: resume.v1.ResumeParserService.ParseResume:input_type -> resume.v1.ParseResumeRequest
	4,  // 13: resume.v1.ResumeParserService.GetParseResult:input_type -> resume.v1.GetParseResultRequest
	6,  // 14: resume.v1.ResumeParserService.ListResumes:input_type -> resume.v1.ListResumesRequest
	8,  // 15: resume.v1.ResumeParserService.DeleteResume:input_type -> resume.v1.DeleteResumeRequest
	10, // 16: resume.v1.AIAnalysisService.AnalyzeResume:input_type -> resume.v1.AnalyzeResumeRequest
	12, // 17: resume.v1.AIAnalysisService.GenerateSuggestions:input_type -> resume.v1.GenerateSuggestionsRequest
	14, // 18: resume.v1.AIAnalysisService.GetAnalysisResult:input_type -> resume.v1.GetAnalysisResultRequest
	1,  // 19: resume.v1.ResumeParserService.UploadResume:output_type -> resume.v1.UploadResumeResponse
	3,  // 20: resume.v1.ResumeParserService.ParseResume:output_type -> resume.v1.ParseResumeResponse
	5,  // 21: resume.v1.ResumeParserService.GetParseResult:output_type -> resume.v1.GetParseResultResponse
	7,  // 22: resume.v1.ResumeParserService.ListResumes:output_type -> resume.v1.ListResumesResponse
	9,  // 23: resume.v1.ResumeParserService.DeleteResume:output_type -> resume.v1.DeleteResumeResponse
	11, // 24: resume.v1.AIAnalysisService.AnalyzeResume:output_type -> resume.v1.AnalyzeResumeResponse
	13, // 25: resume.v1.AIAnalysisService.GenerateSuggestions:output_type -> resume.v1.GenerateSuggestionsResponse
	15, // 26: resume.v1.AIAnalysisService.GetAnalysisResult:output_type -> resume.v1.GetAnalysisResultResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_backend_shared_proto_resume_resume_proto_init() }
func file_backend_shared_proto_resume_resume_proto_init() {
	if File_backend_shared_proto_resume_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_shared_proto_resume_resume_proto_rawDesc), len(file_backend_shared_proto_resume_resume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_backend_shared_proto_resume_resume_proto_goTypes,
		DependencyIndexes: file_backend_shared_proto_resume_resume_proto_depIdxs,
		MessageInfos:      file_backend_shared_proto_resume_resume_proto_msgTypes,
	}.Build()
	File_backend_shared_proto_resume_resume_proto = out.File
	file_backend_shared_proto_resume_resume_proto_goTypes = nil
	file_backend_shared_proto_resume_resume_proto_depIdxs = nil
}
