server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s

data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3307)/resume_optim?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

storage:
  type: local  # local 或 minio
  local:
    path: ./uploads
  minio:
    endpoint: 127.0.0.1:9000
    access_key: minioadmin
    secret_key: minioadmin
    bucket: resume-files
    secure: false
  max_file_size: 10485760  # 10MB
  allowed_types:
    - pdf
    - docx
    - md

registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http
