server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s

data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3307)/resume_optim?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http

ai:
  model:
    provider: ark
    api_key: 375a73e4-4297-463c-80a6-d96df3c380a0
    base_url: https://ark.cn-beijing.volces.com/api/v3
    model_name: doubao-1-5-pro-32k-250115
    max_tokens: 4096
    temperature: 0.7
    timeout_seconds: 60
  
  embedding:
    provider: ark
    api_key: 375a73e4-4297-463c-80a6-d96df3c380a0
    base_url: https://ark.cn-beijing.volces.com/api/v3
    model_name: doubao-embedding-text-240715
    dimension: 1024
    
  eino:
    enable_tracing: true
    enable_caching: true
    max_concurrent: 10
    log_level: debug
  
  vector:
    provider: milvus
    address: 127.0.0.1:19530
    collection_name: resume_knowledge
    dimension: 1024
    similarity_threshold: 0.7
