// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.27.3
// source: file/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileService的错误码
type ErrorReason int32

const (
	// 文件不存在
	ErrorReason_FILE_NOT_FOUND ErrorReason = 0
	// 文件格式不支持
	ErrorReason_FILE_FORMAT_NOT_SUPPORTED ErrorReason = 1
	// 文件大小超限
	ErrorReason_FILE_SIZE_EXCEEDED ErrorReason = 2
	// 文件上传失败
	ErrorReason_FILE_UPLOAD_FAILED ErrorReason = 3
	// 文件下载失败
	ErrorReason_FILE_DOWNLOAD_FAILED ErrorReason = 4
	// 权限不足
	ErrorReason_PERMISSION_DENIED ErrorReason = 5
	// 存储空间不足
	ErrorReason_STORAGE_QUOTA_EXCEEDED ErrorReason = 6
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "FILE_NOT_FOUND",
		1: "FILE_FORMAT_NOT_SUPPORTED",
		2: "FILE_SIZE_EXCEEDED",
		3: "FILE_UPLOAD_FAILED",
		4: "FILE_DOWNLOAD_FAILED",
		5: "PERMISSION_DENIED",
		6: "STORAGE_QUOTA_EXCEEDED",
	}
	ErrorReason_value = map[string]int32{
		"FILE_NOT_FOUND":            0,
		"FILE_FORMAT_NOT_SUPPORTED": 1,
		"FILE_SIZE_EXCEEDED":        2,
		"FILE_UPLOAD_FAILED":        3,
		"FILE_DOWNLOAD_FAILED":      4,
		"PERMISSION_DENIED":         5,
		"STORAGE_QUOTA_EXCEEDED":    6,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_file_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_file_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_file_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_file_v1_error_reason_proto protoreflect.FileDescriptor

const file_file_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1afile/v1/error_reason.proto\x12\vapi.file.v1\x1a\x13errors/errors.proto*\xed\x01\n" +
	"\vErrorReason\x12\x18\n" +
	"\x0eFILE_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12#\n" +
	"\x19FILE_FORMAT_NOT_SUPPORTED\x10\x01\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12FILE_SIZE_EXCEEDED\x10\x02\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12FILE_UPLOAD_FAILED\x10\x03\x1a\x04\xa8E\xf4\x03\x12\x1e\n" +
	"\x14FILE_DOWNLOAD_FAILED\x10\x04\x1a\x04\xa8E\xf4\x03\x12\x1b\n" +
	"\x11PERMISSION_DENIED\x10\x05\x1a\x04\xa8E\x93\x03\x12 \n" +
	"\x16STORAGE_QUOTA_EXCEEDED\x10\x06\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03BUZSgithub.com/liyubo06/resumeOptim_claude/backend/services/file-service/api/file/v1;v1b\x06proto3"

var (
	file_file_v1_error_reason_proto_rawDescOnce sync.Once
	file_file_v1_error_reason_proto_rawDescData []byte
)

func file_file_v1_error_reason_proto_rawDescGZIP() []byte {
	file_file_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_file_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_v1_error_reason_proto_rawDesc), len(file_file_v1_error_reason_proto_rawDesc)))
	})
	return file_file_v1_error_reason_proto_rawDescData
}

var file_file_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.file.v1.ErrorReason
}
var file_file_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_v1_error_reason_proto_init() }
func file_file_v1_error_reason_proto_init() {
	if File_file_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_error_reason_proto_rawDesc), len(file_file_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_file_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_file_v1_error_reason_proto_enumTypes,
	}.Build()
	File_file_v1_error_reason_proto = out.File
	file_file_v1_error_reason_proto_goTypes = nil
	file_file_v1_error_reason_proto_depIdxs = nil
}
