// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/lyb88999/resume_helper/backend/services/parser-service/internal/biz"
	"github.com/lyb88999/resume_helper/backend/services/parser-service/internal/data"
	"github.com/lyb88999/resume_helper/backend/services/parser-service/internal/server"
	"github.com/lyb88999/resume_helper/backend/services/parser-service/internal/service"
	"github.com/lyb88999/resume_helper/backend/shared/proto/conf"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, parser *conf.Parser, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	parseTaskRepo := data.NewParseTaskRepo(dataData, logger)
	parserUsecase := biz.NewParserUsecase(parseTaskRepo, logger)
	parserService := service.NewParserService(parserUsecase)
	grpcServer := server.NewGRPCServer(confServer, parserService, logger)
	httpServer := server.NewHTTPServer(confServer, parserService, logger)
	registrar := server.NewRegistrar(bootstrap)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
