// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/lyb88999/resume_helper/backend/services/file-service/internal/biz"
	"github.com/lyb88999/resume_helper/backend/services/file-service/internal/data"
	"github.com/lyb88999/resume_helper/backend/services/file-service/internal/server"
	"github.com/lyb88999/resume_helper/backend/services/file-service/internal/service"
	"github.com/lyb88999/resume_helper/backend/shared/proto/conf"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, storage *conf.Storage, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	fileRepo := data.NewFileRepo(dataData, logger)
	storageRepo := data.NewStorageRepo(storage, logger)
	fileUsecase := biz.NewFileUsecase(fileRepo, storageRepo, storage, logger)
	fileService := service.NewFileService(fileUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, fileService, logger)
	httpServer := server.NewHTTPServer(confServer, fileService, logger)
	registrar := server.NewRegistrar(bootstrap)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
